apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fscart-prod



commonLabels:
  env: prod

commonAnnotations:
  deployment-environment: prod

images:
- name: REGISTRY/fscart
  newName: fathimasalam/fscart
  newTag: 63a9b7440a240900a49315e620e32f8388178e4e

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: fscart

configMapGenerator:
- behavior: merge
  literals:
  - ENV=production
  - LOG_LEVEL=warn
  - DEBUG=false
  - WORKERS=8
  - CORS_ORIGINS=https://fscart.example.com
  name: fscart-config

replicas:
- count: 3
  name: fscart
resources:
- ../../base
