apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fscart

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app: fscart
  managed-by: kustomize
