apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fscart-dev

resources:
  - ../../base

images:
  - name: REGISTRY/fscart
    newName: fathimasalam/fscart
    newTag: dev

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: fscart

replicas:
  - name: fscart
    count: 1
