apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fscart-dev

bases:
  - ../../base

namePrefix: ""
nameSuffix: ""

commonLabels:
  env: dev

commonAnnotations:
  deployment-environment: dev

images:
  - name: REGISTRY/fscart
    newName: REGISTRY/fscart
    newTag: dev

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: fscart

configMapGenerator:
  - name: fscart-config
    behavior: merge
    literals:
      - ENV=development
      - LOG_LEVEL=debug
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000

replicas:
  - name: fscart
    count: 1
