apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fscart-staging



commonLabels:
  env: staging

commonAnnotations:
  deployment-environment: staging

images:
- name: REGISTRY/fscart
  newName: fathimasalam/fscart
  newTag: 63a9b74

patches:
- path: patch-deployment.yaml
  target:
    kind: Deployment
    name: fscart

configMapGenerator:
- behavior: merge
  literals:
  - ENV=staging
  - LOG_LEVEL=info
  - DEBUG=false
  - CORS_ORIGINS=https://staging.fscart.example.com
  name: fscart-config

replicas:
- count: 2
  name: fscart
resources:
- ../../base
